apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-gateway
  namespace: loyalty-platform
  labels:
    app: api-gateway
    app.kubernetes.io/name: api-gateway
    app.kubernetes.io/part-of: loyalty-platform
automountServiceAccountToken: false
