apiVersion: v1
kind: ServiceAccount
metadata:
  name: admin-web
  namespace: loyalty-platform
  labels:
    app: admin-web
    app.kubernetes.io/name: admin-web
    app.kubernetes.io/part-of: loyalty-platform
automountServiceAccountToken: false
