apiVersion: v1
kind: Service
metadata:
  name: admin-web
  namespace: loyalty-platform
  labels:
    app: admin-web
    app.kubernetes.io/name: admin-web
    app.kubernetes.io/part-of: loyalty-platform
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app: admin-web
