apiVersion: v1
kind: ServiceAccount
metadata:
  name: member-web
  namespace: loyalty-platform
  labels:
    app: member-web
    app.kubernetes.io/name: member-web
    app.kubernetes.io/part-of: loyalty-platform
automountServiceAccountToken: false
