export enum ErrorCodes {
  AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
  AUTH_TOKEN_EXPIRED = 'AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_REVOKED = 'AUTH_TOKEN_REVOKED',
  AUTH_ACCOUNT_LOCKED = 'AUTH_ACCOUNT_LOCKED',
  AUTH_TOO_MANY_ATTEMPTS = 'AUTH_TOO_MANY_ATTEMPTS',
  AUTH_TOKEN_INVALID = 'AUTH_TOKEN_INVALID',
  AUTH_WEAK_PASSWORD = 'AUTH_WEAK_PASSWORD',

  FORBIDDEN = 'FORBIDDEN',
  TENANT_SUSPENDED = 'TENANT_SUSPENDED',
  TENANT_CROSS_ACCESS = 'TENANT_CROSS_ACCESS',

  NOT_FOUND = 'NOT_FOUND',
  CONFLICT = 'CONFLICT',
  VALIDATION_ERROR = 'VALIDATION_ERROR',

  LIMIT_EXCEEDED = 'LIMIT_EXCEEDED',
  PLAN_LIMIT_EXCEEDED = 'PLAN_LIMIT_EXCEEDED',

  INSUFFICIENT_POINTS = 'INSUFFICIENT_POINTS',
  INSUFFICIENT_BALANCE = 'INSUFFICIENT_BALANCE',
  POINTS_EXPIRED = 'POINTS_EXPIRED',

  OUT_OF_STOCK = 'OUT_OF_STOCK',
  ALREADY_REDEEMED = 'ALREADY_REDEEMED',
  ALREADY_USED = 'ALREADY_USED',
  ALREADY_REFUNDED = 'ALREADY_REFUNDED',

  EXPIRED = 'EXPIRED',
  CONDITIONS_NOT_MET = 'CONDITIONS_NOT_MET',
  POOL_EXHAUSTED = 'POOL_EXHAUSTED',
  SELF_REFERRAL = 'SELF_REFERRAL',
  NOT_COMPLETED = 'NOT_COMPLETED',
  CANNOT_CANCEL = 'CANNOT_CANCEL',

  RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED',
  SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
}

export class ServiceException extends Error {
  constructor(
    message: string,
    public code: ErrorCodes,
    public httpStatus: number = 400,
  ) {
    super(message);
    this.name = 'ServiceException';
  }
}
